export const ALL_COMPLAINTS_REQUEST = "ALL_COMPLAINTS_REQUEST";
export const ALL_COMPLAINTS_SUCCESS = "ALL_COMPLAINTS_SUCCESS";
export const ALL_COMPLAINTS_FAIL = "ALL_COMPLAINTS_FAIL";

export const ADMIN_COMPLAINTS_REQUEST = "ADMIN_COMPLAINTS_REQUEST";
export const ADMIN_COMPLAINTS_SUCCESS = "ADMIN_COMPLAINTS_SUCCESS";
export const ADMIN_COMPLAINTS_FAIL = "ADMIN_COMPLAINTS_FAIL";

export const NEW_COMPLAINTS_REQUEST = "NEW_COMPLAINTS_REQUEST";
export const NEW_COMPLAINTS_SUCCESS = "NEW_COMPLAINTS_SUCCESS";
export const NEW_COMPLAINTS_RESET = "NEW_COMPLAINTS_RESET";
export const NEW_COMPLAINTS_FAIL = "NEW_COMPLAINTS_FAIL";

export const UPDATE_COMPLAINTS_REQUEST = "UPDATE_COMPLAINTS_REQUEST";
export const UPDATE_COMPLAINTS_SUCCESS = "UPDATE_COMPLAINTS_SUCCESS";
export const UPDATE_COMPLAINTS_RESET = "UPDATE_COMPLAINTS_RESET";
export const UPDATE_COMPLAINTS_FAIL = "UPDATE_COMPLAINTS_FAIL";

export const DELETE_COMPLAINTS_REQUEST = "DELETE_COMPLAINTS_REQUEST";
export const DELETE_COMPLAINTS_SUCCESS = "DELETE_COMPLAINTS_SUCCESS";
export const DELETE_COMPLAINTS_RESET = "DELETE_COMPLAINTS_RESET";
export const DELETE_COMPLAINTS_FAIL = "DELETE_COMPLAINTS_FAIL";

export const COMPLAINTS_DETAILS_REQUEST = "COMPLAINTS_DETAILS_REQUEST";
export const COMPLAINTS_DETAILS_SUCCESS = "COMPLAINTS_DETAILS_SUCCESS";
export const COMPLAINTS_DETAILS_FAIL = "COMPLAINTS_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";